import numpy as np

# Regression
def r2_score(y, y_pred): ...
def mse(y, y_pred): ...        # mean squared error
def rmse(y, y_pred): ...       # root mse
def mae(y, y_pred): ...        # mean absolute error

# Classification (add later)
def accuracy(y, y_pred): ...
def precision(y, y_pred): ...
def recall(y, y_pred): ...
def f1(y, y_pred): ...